### ISSUE TITLE
Request example dataset

### ISSUE THREAD

**Issue by iuimaki** [yixiangD/AccurateBG#1]
Hi  the ohioT1DM dataset now is not public. I request the data use agreement for the ohioT1DM dataset. But I am not sure they will approve, as I am just a student, not a researcher. I wonder if you could share another example dataset on Github.

**Comment by yixiangD** [comment]
Hi there,

Thanks for you interest in the repo. Unfortunately, due to the restriction imposed by OhioT1DM application, we, as the applicants, could not redistribute the dataset. 
There are few other ways to use the code.
1) If you would like to use OhioT1DM, I encourage you to apply with the help of your academic advisor, who is a PI. There is no cost for the application, so I think this is the best solution.
2) If you just want to test some time-series data, there are readily available time-series data in the author implemented [TImeGAN repo](https://github.com/jsyoon0823/TimeGAN).

Hope this helps!

**Comment by Erlend25** [comment]
My friend @yixiangD I also have the same problem as my colleague. However, I do not know if you could share the dataset with us but with a line of record, I have no problem that the only record is with fictitious data (not to violate the sensitive data), what I want is that the folder that I must put in "data" has the same structure and formats. The truth is that I am a student who loves the world of deep learning and I am fascinated with your project.
Thank you very much in advance for reading me.

**Comment by yixiangD** [comment]
Hi there, 
Apologies for the late response. I recommend exploring some T1D simulators for example UVA/Pandova (based on a compartment model) to generate glucose data. One possibly useful repository on GitHub is [simglucose](https://github.com/jxx123/simglucose). Good luck!
